### ISSUE TITLE
Web Hook isn't called when webmention is received

### ISSUE THREAD

**Issue by dogada** [aaronpk/webmention.io#69]
Is there any delay between receiving of webmention by webmention.io and calling web hook? It looks like web hook is called with some big delay. For example for https://dogada.org using https://webmention.io/api/mentions I can see several new webmentions sent today from Brid.gy but I don't see in my server logs that web hook was called by webmention.io even once today.

**Comment by aaronpk** [comment]
It should be called pretty much instantly. I looked at the logs and it looks like there was an error with some of them when the source URL doesn't contain a publish date. (Facebook doesn't provide the date of a like action.) I just fixed that, so you should be seeing more web hooks now!

**Comment by dogada** [comment]
Thanks, Aaron, but to check the fix I need to write something interesting and publish the link on facebook to get some likes ;)

**Comment by dogada** [comment]
Looks like the mentions stuck in the processing queue. Bridgy sent me webmention a hour ago but I still don't see it: https://brid.gy/log?start_time=1456592732&key=aglzfmJyaWQtZ3lyNQsSCFJlc3BvbnNlIid0YWc6dHdpdHRlci5jb20sMjAxMzo3MDM1MzA1NTM5ODM4MTE1ODQM

I also tried to sent webmentions using https://webmention.io/dogada.org/webmention endpoint and also don't see them in logs.

Is there somewhere any public log where state of my webmentions can be tracked (smth like Brid.gy has)?

**Comment by aaronpk** [comment]
The server got another flood of webmentions this morning which is causing the slowness you're seeing. I just added some rate limiting that will help keep some of the flooding out in the first place.

I am planning on providing better visibility into what's going on, part of that is providing a status page for webmentions in #37

**Comment by dogada** [comment]
Thanks, Aaron, my web hook started to receive data.

**Comment by aaronpk** [comment]
That's great to hear! I've been working on some other optimizations as well, so hopefully this doesn't keep happening.
